[target.riscv64gc-unknown-linux-musl]
linker = "/home/mime/daten/dev/TTR/infrared_milkv/toolchain/bin/riscv64-buildroot-linux-musl-gcc.br_real"
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=--sysroot=toolchain/riscv64-buildroot-linux-musl/sysroot",
    # "-C", "target-feature=+crt-static", # Uncomment me to force static compilation
    # "-C", "panic=abort", # Uncomment me to avoid compiling in panics
]

[env]
CC = { value = "toolchain/bin/riscv64-buildroot-linux-musl-gcc", relative = true }
CXX = { value = "toolchain/bin/riscv64-buildroot-linux-musl-g++", relative = true }

[build]
target = "riscv64gc-unknown-linux-musl"